name: Disk Utility CI/CD Build

on:
    push:
        branches: [ "master" ]
    pull_request:
        branches: [ "master" ]

jobs:
    build:
        strategy:
            matrix:
                configuration: [ Debug, Release ]

        runs-on: windows-latest

        steps:
        - name: Checkout
          uses: actions/checkout@v4
          with:
            fetch-depth: 0
            
        - name: Install .NET Core
          uses: actions/setup-dotnet@v4
          with:
            dotnet-version: 8.0.x

        - name: Run Build
          shell: pwsh
          run: ./build.ps1 --configuration ${{ matrix.configuration }}

        - uses: actions/upload-artifact@v4
          with:
            name: installer
            path: .nuke/Artifacts/Installer/*
