name: Disk Utility CI/CD Build

on:
    push:
        branches: [ "master" ]
    pull_request:
        branches: [ "master" ]

jobs:
    build:
        strategy:
            matrix:
                configuration: [ Debug, Release ]

        runs-on: windows-latest

        steps:
        - name: Checkout
          uses: actions/checkout@v4
          with:
            fetch-depth: 0
            
        - name: Install .NET Core
          uses: actions/setup-dotnet@v4
          with:
            dotnet-version: 8.0.x

        - name: Run Build
          shell: pwsh
          run: ./build.ps1 --configuration ${{ matrix.configuration }}

        - name: Upload the installer package
          uses: actions/upload-artifact@v4
          if: ${{ matrix.configuration == 'Release' }}
          with:
            name: Installer Package
            path: .nuke/Artifacts/Installer
            if-no-files-found: error

        - name: Upload the coverage report as artifact
          uses: actions/upload-artifact@v4
          with:
            name: Coverage Report ${{ matrix.configuration }}
            path: .nuke/Artifacts/Coverage-Report
            compression-level: 9
            if-no-files-found: error

        - name: Setup Github Pages
          if: github.ref == 'refs/heads/master'
          uses: actions/configure-pages@v3

        - name: Upload the coverage report for github pages
          if: github.ref == 'refs/heads/master'
          uses: actions/upload-pages-artifact@v1
          with:
            path: .nuke/Artifacts/Coverage-Report

    deploy-coverage:
        if: github.ref == 'refs/heads/master'
        runs-on: ubuntu-latest
        needs: build

        permissions:
            pages: write
            id-token: write

        environment:
            name: github-pages
            url: ${{ steps.deployment.outputs.page_url }}

        steps:
        - name: Deploy to Github Pages
          id: deployment
          uses: actions/deploy-pages@v2


